# Generated by Django 3.0.6 on 2020-06-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_ref', models.PositiveIntegerField(default=0)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('games_won', models.PositiveIntegerField(default=0)),
                ('times_placed', models.PositiveIntegerField(default=0)),
                ('net_winnings', models.IntegerField(default=0)),
                ('average_placing', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('score', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
