# Generated by Django 3.0.6 on 2020-06-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='scorable',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
