# Generated by Django 3.0.6 on 2020-06-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_game_scorable'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='average_rating',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stats',
            name='place_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='place_2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='place_3',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
