# Generated by Django 3.0.7 on 2020-12-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0005_auto_20200621_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='big_blind',
        ),
        migrations.RemoveField(
            model_name='round',
            name='game',
        ),
        migrations.RemoveField(
            model_name='round',
            name='small_blind',
        ),
        migrations.RemoveField(
            model_name='round',
            name='table',
        ),
        migrations.RemoveField(
            model_name='roundwinner',
            name='game',
        ),
        migrations.RemoveField(
            model_name='roundwinner',
            name='round',
        ),
        migrations.RemoveField(
            model_name='roundwinner',
            name='table',
        ),
        migrations.RemoveField(
            model_name='roundwinner',
            name='table_participant',
        ),
        migrations.DeleteModel(
            name='Hand',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.DeleteModel(
            name='RoundWinner',
        ),
    ]
