# Generated by Django 3.0.7 on 2021-01-03 11:52

from django.db import migrations, models
import django.db.models.deletion


def create_competition(apps, schema_editor):
    Competition = apps.get_model('poker', 'Competition')
    comp = Competition(name='2020 Covid Poker', order=1, active=True)
    comp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0006_auto_20201230_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_ref', models.PositiveIntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='poker.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.Competition')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.Game')),
            ],
        ),
        migrations.RunPython(create_competition)
    ]
