# Generated by Django 3.0.7 on 2021-01-03 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0007_competition_competitiongame_competitionparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poker.Competition'),
        ),
        migrations.AlterField(
            model_name='competitiongame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='poker.Game'),
        ),
    ]
