# Generated by Django 3.0.7 on 2021-01-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0008_auto_20210103_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='new_score',
            field=models.IntegerField(default=0),
        ),
    ]
