# Generated by Django 3.0.6 on 2020-05-25 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pokerth_name', models.CharField(max_length=255)),
                ('avatar', models.URLField()),
                ('payment_link', models.URLField()),
                ('payment_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=30)),
                ('bank_sort_code', models.CharField(max_length=6)),
                ('active', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentObligation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_ref', models.PositiveIntegerField(default=0)),
                ('payment_amount', models.PositiveIntegerField(default=0)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='players.Player')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='players.Player')),
            ],
        ),
    ]
