# Generated by Django 3.0.6 on 2020-06-15 01:33

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarupload',
            name='file',
            field=models.FileField(upload_to=upload.models.upload_path),
        ),
    ]
