# Generated by Django 3.0.6 on 2020-05-24 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.PositiveIntegerField(default=1)),
                ('date_played', models.DateField()),
                ('stake', models.PositiveIntegerField(default=0)),
                ('place_two_multiplier', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('place_three_multiplier', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_ref', models.PositiveIntegerField(default=0)),
                ('place', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('blind_amount', models.PositiveIntegerField(default=0)),
                ('flop1', models.PositiveIntegerField(default=0)),
                ('flop3', models.PositiveIntegerField(default=0)),
                ('flop2', models.PositiveIntegerField(default=0)),
                ('turn', models.PositiveIntegerField(default=0)),
                ('river', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('designation', models.CharField(max_length=10)),
                ('starting_chips', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.Game')),
            ],
        ),
        migrations.CreateModel(
            name='TableParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('game_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.GameParticipant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.Table')),
            ],
        ),
        migrations.CreateModel(
            name='RoundWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chips_won', models.PositiveIntegerField(default=0)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.Round')),
                ('table_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.TableParticipant')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='big_blind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='poker.TableParticipant'),
        ),
        migrations.AddField(
            model_name='round',
            name='small_blind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='poker.TableParticipant'),
        ),
        migrations.AddField(
            model_name='round',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.Table'),
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card1', models.PositiveIntegerField(default=0)),
                ('card2', models.PositiveIntegerField(default=0)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.Round')),
                ('table_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.TableParticipant')),
            ],
        ),
    ]
