# Generated by Django 3.0.6 on 2020-05-31 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poker.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hand',
            name='table',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='poker.Table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='game',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='poker.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roundwinner',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poker.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roundwinner',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poker.Table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tableparticipant',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poker.Game'),
            preserve_default=False,
        ),
    ]
