# Generated by Django 3.0.6 on 2020-06-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_auto_20200531_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='progressing',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gameparticipant',
            name='place',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='starting_chips',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
