# Generated by Django 3.0.6 on 2020-06-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_auto_20200601_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='complete',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='tableparticipant',
            name='success',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
