# Generated by Django 3.0.6 on 2020-06-15 07:09

import os
from django.db import migrations

def create_super_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if os.getenv('SUPERUSER_NAME'):
        if not User.objects.filter(username= os.getenv('SUPERUSER_NAME')).exists():
            instance = User(username=os.getenv('SUPERUSER_NAME'), password=os.getenv('SUPERUSER_PASSWORD'), email=os.getenv('SUPERUSER_EMAIL'), is_active=True, is_superuser=True)
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_super_user),
    ]
