# Generated by Django 3.0.7 on 2021-01-03 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='players.Player'),
        ),
    ]
