# Generated by Django 3.0.6 on 2020-06-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20200530_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentobligation',
            name='payment_confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='paymentobligation',
            name='payment_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
